# Generated by Django 5.2.4 on 2025-07-17 11:57

import partial_date.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballFederationM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fed_Name', models.CharField(max_length=20)),
                ('Type_Fed', models.CharField(choices=[('GL', 'GLOBAL'), ('CN', 'CONTINENTAL')], max_length=2)),
                ('Founded_Year', partial_date.fields.PartialDateField()),
                ('Members', models.IntegerField(help_text='Dont counting associate members')),
                ('Associate_Member', models.IntegerField(blank=True, default=0, help_text='Members who not full join to federation. Default value 0')),
                ('Main_tournament', models.CharField()),
            ],
        ),
    ]
