# Generated by Django 5.2.4 on 2025-07-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballcompetition',
            name='Type_Competition',
            field=models.CharField(choices=[('T', 'TOURNIRE'), ('L', 'LEAGUE')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footballleague',
            name='League_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.footballcompetition'),
        ),
    ]
