# Generated by Django 5.2.4 on 2025-07-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Competition_Name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeagueName', models.CharField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='footballfederationm',
            options={'verbose_name': 'FootballFederation', 'verbose_name_plural': 'FootballFederations'},
        ),
        migrations.CreateModel(
            name='CountryFootball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField()),
                ('Tournament_In_Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.footballcompetition')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
