# Generated by Django 5.2.4 on 2025-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrylist',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
    ]
