# Generated by Django 5.2.4 on 2025-07-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbincident',
            name='id',
        ),
        migrations.AddField(
            model_name='fbincident',
            name='slugtitlesaver_ptr',
            field=models.OneToOneField(auto_created=True, default='none', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.slugtitlesaver'),
            preserve_default=False,
        ),
    ]
