# Generated by Django 5.2.4 on 2025-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_footballcompetition_footballleague_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryfootball',
            name='Tournament_In_Country',
        ),
        migrations.AddField(
            model_name='countryfootball',
            name='Tournament_In_Country',
            field=models.ManyToManyField(related_name='countries', to='db.footballcompetition'),
        ),
    ]
