# Generated by Django 5.2.4 on 2025-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_countrylist_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeIncedent',
            new_name='TypeIncident',
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='country_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
