# Generated by Django 5.2.4 on 2025-07-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_fbcompetition_fbfederation_fbleague_fbseason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryFootball',
            new_name='FbCountryFed',
        ),
    ]
