# Generated by Django 5.2.4 on 2025-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_countryfootball_fbcountryfed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_association_name', models.CharField(max_length=100)),
                ('short_association_name', models.CharField(max_length=10)),
                ('tournament_in_country', models.ManyToManyField(related_name='countries', to='db.fbcompetition')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.DeleteModel(
            name='FbCountryFed',
        ),
    ]
