# Generated by Django 5.2.4 on 2025-07-17 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_fbcountry_delete_fbcountryfed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleague',
            name='country_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.fbcountry'),
        ),
    ]
