# Generated by Django 5.2.4 on 2025-07-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_fbcompetition_options_alter_fbcountry_options_and_more'),
    ]

    operations = [
    ]
