# Generated by Django 5.2.4 on 2025-07-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20250718_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbmatch',
            options={'verbose_name': 'Football Match', 'verbose_name_plural': 'Football Матчи'},
        ),
        migrations.AlterField(
            model_name='fbmatch',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='db.fbteam'),
        ),
        migrations.AlterField(
            model_name='fbmatch',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='db.fbteam'),
        ),
        migrations.CreateModel(
            name='FbIncedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_where_incedent_make', models.PositiveIntegerField()),
                ('is_own_goal', models.BooleanField()),
                ('is_home', models.BooleanField()),
                ('incedent_type', models.CharField(choices=[('YC', 'Yellow Card'), ('RC', 'Red Card'), ('PEN', 'in Game Penalty'), ('MP', 'Missed Penalty'), ('GP', 'Penalty Goal'), ('SP', 'Penalty Shootout'), ('S', 'Substitution'), ('I', 'Injury'), ('OG', 'Own Goal'), ('V', 'VAR'), ('IJ', 'Injury Time'), ('P', 'Period'), ('GC', 'Goal Cancelled')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('reason', models.CharField(max_length=50)),
                ('match_where_incedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.fbmatch')),
            ],
            options={
                'verbose_name': 'Football Incedent',
                'verbose_name_plural': 'Football Incedents',
            },
        ),
        migrations.CreateModel(
            name='FbPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('jersey_number', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=5)),
                ('height', models.PositiveIntegerField()),
                ('date_of_birthday', models.DateField()),
                ('prefered_foot', models.CharField()),
                ('national', models.CharField(max_length=50)),
                ('played_in_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.fbteam')),
            ],
            options={
                'verbose_name': 'Football Player',
                'verbose_name_plural': 'Football Players',
            },
        ),
        migrations.CreateModel(
            name='FbGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incedent_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.fbincedent')),
                ('player_who_assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_assist', to='db.fbplayer')),
                ('player_who_scored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scored', to='db.fbplayer')),
            ],
            options={
                'verbose_name': 'Football Goal',
                'verbose_name_plural': 'Football Goals',
            },
        ),
        migrations.CreateModel(
            name='FbSubtitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incedent_subtitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.fbincedent')),
                ('player_who_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in', to='db.fbplayer')),
                ('player_who_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_out', to='db.fbplayer')),
            ],
            options={
                'verbose_name': 'Football Subtitution',
                'verbose_name_plural': 'Football Subtitutions',
            },
        ),
    ]
