# Generated by Django 5.2.4 on 2025-07-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_fbmatch_options_alter_fbmatch_away_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbmatch',
            options={'verbose_name': 'Football Match', 'verbose_name_plural': 'Football Matches'},
        ),
        migrations.AlterField(
            model_name='fbincedent',
            name='incedent_type',
            field=models.CharField(choices=[('YC', 'Yellow Card'), ('RC', 'Red Card'), ('PEN', 'in Game Penalty'), ('MP', 'Missed Penalty'), ('GP', 'Penalty Goal'), ('SP', 'Penalty Shootout'), ('S', 'Substitution'), ('I', 'Injury'), ('OG', 'Own Goal'), ('V', 'VAR'), ('IJ', 'Injury Time'), ('P', 'Period'), ('GC', 'Goal Cancelled'), ('G', 'Goal')], max_length=3),
        ),
        migrations.AlterField(
            model_name='fbincedent',
            name='reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='fbteam',
            name='league_where_play_team',
        ),
        migrations.AlterUniqueTogether(
            name='fbstandings',
            unique_together={('season_year', 'team')},
        ),
        migrations.AddField(
            model_name='fbteam',
            name='league_where_play_team',
            field=models.ManyToManyField(to='db.fbcompetition'),
        ),
    ]
