# Generated by Django 5.2.4 on 2025-07-19 10:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_fbmatch_options_alter_fbincedent_incedent_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutnry_name', models.CharField(max_length=150)),
                ('iso_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIncedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_incedent', models.CharField(max_length=50)),
                ('description_incedent', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='difference_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='draw_match_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='last_five_match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, default=list, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='losse_match_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='match_played_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='missed_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='scored_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fbstandings',
            name='win_match_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
