# Generated by Django 5.2.4 on 2025-07-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_countrylist_typeincedent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrylist',
            old_name='coutnry_name',
            new_name='country_name',
        ),
        migrations.AlterField(
            model_name='fbcountry',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.countrylist'),
        ),
        migrations.AlterField(
            model_name='fbincedent',
            name='incedent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.typeincedent'),
        ),
        migrations.AlterField(
            model_name='fbleague',
            name='country_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.countrylist'),
        ),
        migrations.AlterField(
            model_name='fbplayer',
            name='national',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.countrylist'),
        ),
        migrations.AlterField(
            model_name='typeincedent',
            name='description_incedent',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
