# Generated by Django 5.2.4 on 2025-07-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_rename_coutnry_name_countrylist_country_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbleague',
            name='country_league',
        ),
        migrations.AddField(
            model_name='fbleague',
            name='coutnry_league',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fbleague',
            name='new_country_league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db.countrylist'),
            preserve_default=False,
        ),
    ]
