# Generated by Django 5.2.4 on 2025-07-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_remove_fbleague_country_league_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbleague',
            old_name='new_country_league',
            new_name='country_league',
        ),
        migrations.RemoveField(
            model_name='fbleague',
            name='coutnry_league',
        ),
    ]
