# Generated by Django 5.2.4 on 2025-07-19 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_rename_new_country_league_fbleague_country_league_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FbIncedent',
            new_name='FbIncident',
        ),
        migrations.AlterModelOptions(
            name='countrylist',
            options={'ordering': ['country_name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fbcountry',
            options={'ordering': ['country_name'], 'verbose_name': 'Football Country', 'verbose_name_plural': 'Football Countries'},
        ),
        migrations.AlterModelOptions(
            name='fbincident',
            options={'verbose_name': 'Football Incident', 'verbose_name_plural': 'Football Incidents'},
        ),
        migrations.AlterModelOptions(
            name='typeincedent',
            options={'ordering': ['name_incedent'], 'verbose_name': 'Incedent', 'verbose_name_plural': 'Incedents'},
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='iso_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='fbplayer',
            name='jersey_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fbplayer',
            name='position',
            field=models.CharField(choices=[('GK', 'GOALKEEPER'), ('D', 'DEFENDER'), ('M', 'MIDFIELDER'), ('F', 'FORWARD')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fbplayer',
            name='prefered_foot',
            field=models.CharField(choices=[('L', 'LEFT'), ('R', 'RIGHT'), ('B', 'BOTH')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='fbstandings',
            unique_together={('season_year', 'team', 'standing_league')},
        ),
    ]
