# Generated by Django 5.2.4 on 2025-07-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_rename_fbincedent_fbincident_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FbSubtitution',
            new_name='FbSubstitution',
        ),
        migrations.AlterModelOptions(
            name='fbcompetition',
            options={'ordering': ['competition_name'], 'verbose_name': 'Football Competition', 'verbose_name_plural': 'Football Competitions'},
        ),
        migrations.AlterModelOptions(
            name='fbsubstitution',
            options={'verbose_name': 'Football substitution', 'verbose_name_plural': 'Football substitutions'},
        ),
        migrations.RenameField(
            model_name='fbstandings',
            old_name='losse_match_count',
            new_name='lost_match_count',
        ),
        migrations.RenameField(
            model_name='fbsubstitution',
            old_name='incedent_subtitution',
            new_name='incedent_substitution',
        ),
        migrations.AlterField(
            model_name='fbcompetition',
            name='type_competition',
            field=models.CharField(blank=True, choices=[('T', 'TOURNAMENT'), ('L', 'LEAGUE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fbmatch',
            name='match_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fbseason',
            name='name_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='db.fbleague'),
        ),
    ]
