# Generated by Django 5.2.4 on 2025-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_rename_fbsubtitution_fbsubstitution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbIncidentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_incident', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Football Incident Class',
                'verbose_name_plural': 'Football Incident Clases',
                'ordering': ['class_incident'],
            },
        ),
    ]
