# Generated by Django 5.2.4 on 2025-07-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_fbincidentclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FbIncidentClass',
            new_name='IncidentClass',
        ),
    ]
