# Generated by Django 5.2.4 on 2025-07-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_rename_fbincidentclass_incidentclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbincident',
            old_name='incedent_type',
            new_name='incident_type',
        ),
        migrations.AddField(
            model_name='fbincident',
            name='incident_class',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='db.incidentclass'),
            preserve_default=False,
        ),
    ]
