# Generated by Django 5.2.4 on 2025-07-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_rename_incedent_type_fbincident_incident_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeincedent',
            options={'ordering': ['name_incident'], 'verbose_name': 'Incedent', 'verbose_name_plural': 'Incedents'},
        ),
        migrations.RenameField(
            model_name='typeincedent',
            old_name='description_incedent',
            new_name='description_incident',
        ),
        migrations.RenameField(
            model_name='typeincedent',
            old_name='name_incedent',
            new_name='name_incident',
        ),
    ]
