# Generated by Django 5.2.4 on 2025-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_alter_typeincedent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentclass',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
